from enum import StrEnum


class EvidenceStatus(StrEnum):
    PENDING = "PENDING"
    VALIDATING = "VALIDATING"
    PROCESSING = "PROCESSING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    COMPLETE = "COMPLETE"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class JobType(StrEnum):
    PROCESS_EVIDENCE = "PROCESS_EVIDENCE"
    RECOMPUTE_SCORE = "RECOMPUTE_SCORE"


class DetectedSource(StrEnum):
    BANK_SMS = "BANK_SMS"
    OPAY_SCREENSHOT = "OPAY_SCREENSHOT"
    PALMPAY_SCREENSHOT = "PALMPAY_SCREENSHOT"
    MONIEPOINT_SCREENSHOT = "MONIEPOINT_SCREENSHOT"
    KUDA_SCREENSHOT = "KUDA_SCREENSHOT"
    TELLER_SLIP = "TELLER_SLIP"
    RECEIPT = "RECEIPT"
    PASSBOOK = "PASSBOOK"
    BANK_STATEMENT = "BANK_STATEMENT"
    WHATSAPP_REPAYMENT_CHAT = "WHATSAPP_REPAYMENT_CHAT"
    HANDWRITTEN_DOCUMENT = "HANDWRITTEN_DOCUMENT"
    MANUAL_NOTE = "MANUAL_NOTE"
    UNKNOWN = "UNKNOWN"


class EventType(StrEnum):
    INCOME = "INCOME"
    SPEND = "SPEND"
    REPAYMENT = "REPAYMENT"
    TRANSFER = "TRANSFER"
    BALANCE = "BALANCE"
    DECLARATION = "DECLARATION"
